name: Deploy Calculator in Docker

on:
  push:
    branches:
      - main  # Run workflow when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mycalculator:latest .

      - name: Tag and Push Image to Docker Hub
        run: |
          docker tag mycalculator:latest ${{ secrets.DOCKER_HUB_USERNAME }}/calculator:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/calculator:latest

      - name: Run Docker Container
        run: docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/calculator:latest
